---
- hosts: all
  tasks:
  - name: Load vars from a file
    include_vars:
      dir: vars
      extensions: [yml]
  - name: copy dump to remote
    copy:
      src: dumps/lodstats_dump_13-09-2017_17_20_05.sql.gz
      dest: /tmp/lodstats_dump_13-09-2017_17_20_05.sql.gz
  - name: load lodstats db
    postgresql_db:
      login_host: localhost
      login_user: "{{ POSTGRES_USER }}"
      login_password: "{{ POSTGRES_PASSWORD }}"
      name: "{{ POSTGRES_DB }}"
      state: restore
      target: /tmp/lodstats_dump_13-09-2017_17_20_05.sql.gz