bootstrap:
	ansible-playbook -i hosts bootstrap.yml

download-lodstats-dump:
	echo "https://drive.google.com/uc?export=download&id=1yHOH06I4AjLCi40DrjJNa1-r8CBWHS9M"

load-lodstats-dump:
	ansible-playbook -i hosts load-lodstats-db.yml 
